# Derived from default workflow fo Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test on Maven

on:
  [push, pull_request]

jobs:
  test-baseline:

    runs-on: ubuntu-16.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
         java-version: 1.8
      
      - name: Install GStreamer
        run: sudo apt-get install gstreamer1.0-plugins-good
      
      - name: Build with Maven
        run: mvn -B verify --file pom.xml
